### ISSUE TITLE
Broken Specular Mapping on Skin

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/MiscFixesSSE#3]
This is a forward of a [request by ff7legend on Nexus](https://forums.nexusmods.com/index.php?showtopic=7202046/#entry65690046).

> Please look into fixing the broken specular mapping issue in Skyrim SE. Further details of this horrific bug can be found here:
> https://bethesda.net/community/topic/176991/character-specular-highlight-not-updating-correctly
> This is definitely a vanilla engine bug that was introduced into Skyrim SE. Bethesda has yet to fix this & it's beyond ridiculous/annoying. 

The issue seems to cause specular mapping (reflective highlights on the skin) to only appear from one direction, regardless of what direction the character faces (typically the North side of a cell, according to reports on that link).

The issue does not occur on armor/clothes, just the skin.

**Comment by Ryan-rsm-McKenzie** [comment]
Fixed by aers
