### ISSUE TITLE
Suggestion: Merge into SSE Engine Fixes (or Vice Versa)

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/MiscFixesSSE#4]
So this is just something I was thinking - you could consider either merging all of SSE Engine Fixes into this mod, or alternatively forking SSE Engine Fixes, and adding your changes to it. 

[SSE Engine Fixes is also fully open](https://github.com/aers/EngineFixesSkyrim64) as long as it is not used for a paid product (and you must ask permission to opt it into Donation Points). The last developer of it (Aers) has expressed they have not been motivated to work on Skyrim recently. It would be nice to have a more active maintainer for said project (if for no other reason than updating SSE Engine Fixes to work after SKSE64/SSE version updates).

**Comment by Ryan-rsm-McKenzie** [comment]
Done
