### ISSUE TITLE
Fix Engine Spamming OnObjectEquipped

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/MiscFixesSSE#5]
So apparently, under certain circumstances, the game engine spams the OnObjectEquipped event, instead of using it once as it should. This can lead to crashes if mods use scripts relatively performance intensive scripts on those events.

This was [identified by Ousnius on the RaceMenu threads](https://forums.nexusmods.com/index.php?/topic/6882167-racemenu/page-38#entry62645956), and is [stickied by Groovtama on the XPMSSE threads](https://forums.nexusmods.com/index.php?/topic/5004160-xp32-maximum-skeleton-special-extended-xpmsse/page-209#entry62648076).

**Comment by Ryan-rsm-McKenzie** [comment]
Fixed in 1.3.0
